### ISSUE TITLE
Oblivines absent

### ISSUE THREAD

**Issue by RechercheRaptor** [Lyof429/EndsPhantasm#11]
Oblivines don't appear in the creative inventory, and I can't /give them to myself. I was trying to test how oblifruit spawn/if they can be bonemealed in a test superflat world and I can't figure out how to even start growing them without the vines (bonemealing oblivion hasn't done anything).

I'm on mod version 0.3, minecraft version 1.20.1, forge version 47.3.5.

**Comment by Lyof429** [comment]
On forge the porter decided to make them like how sweet berries work in vanilla, so the thing used to plant them are actually oblifruits
It'll be fixed in some future version but in the meantime this is why, sorry for the inconsistency

**Comment by RechercheRaptor** [comment]
Oh, okay, thank you!

**Comment by RechercheRaptor** [comment]
What do I plant oblifruits on? I've tried top/side/bottom of oblivion, obsidian, endstone, raw purpur, pream leaves, and even farmland, but it won't plant on any of them.

**Comment by Lyof429** [comment]
It should work on the bottom side of endstone, oblivion and other oblivines, this is strange ._.

**Comment by SashaKYotoz** [comment]
All of it was fixed in v0.4. Just update mod from curseforge

**Comment by SashaKYotoz** [comment]
If you use modrinth, it was uploaded too
