### ISSUE TITLE
Elytra broken in 1.20.1

### ISSUE THREAD

**Issue by nytethc** [Lyof429/EndsPhantasm#13]
When trying to use a Rocket mid air, while flying with an Elytra or, e.g Icarus Wings the boost does not work. 
It only works when being on the ground. 

this was tested while using the Mod on Fabric 0.16.0

**Comment by SashaKYotoz** [comment]
It's feature provided by End's Phantasm, to hard gameplay. To unlock boosting you need to get advancement - Free the End.

If you wanna turn this feature off - go to config of mod, and switch 'elytra_boost_advancement' to blank ""
