### ISSUE TITLE
[bug report] Behemoths spawn under the end islands infinately

### ISSUE THREAD

**Issue by Tigerboy007** [Lyof429/EndsPhantasm#16]
The mob 'behemoth' spawns in the 'Dreaming Den' Biome underneath the islands, causing them to fall into void, which then clears the spawn cap for them. This cycle repeats infinitely.

This was found on version 0.4, Minecraft 1.20.1, and forge 47.2.17.

https://github.com/user-attachments/assets/5d967e6e-833a-4983-855b-a874084e8bd8

**Comment by Lyof429** [comment]
This one is known and is fixed for the upcoming patch version, but thanks for reporting anyway
