### ISSUE TITLE
When used with “Higher Nether”, this will be generated at y=256

### ISSUE THREAD

**Issue by shitou0721** [Lyof429/EndsPhantasm#17]
![bug](https://github.com/user-attachments/assets/a48b35e4-6052-484b-b86a-b5f9602be37d)

**Comment by Lyof429** [comment]
Forge I assume? If yes this isn't an issue with higher nether, it's simply that the porter forgot to end the generation of the crystal spikes if it couldn't find an end island on its path from y0
I think it has been fixed in the latest version but I might be wrong and it might be something coming
