### ISSUE TITLE
End's Phantasm End dimension worldgen issue for Forge 1.20.1

### ISSUE THREAD

**Issue by 1tech23** [Lyof429/EndsPhantasm#23]
Hello, I recently made a comment on your modpack on Curseforge. under the name Traitor192004. 

There is no ground on the Ender Dragon arena at coordinate 0, ~, 0 (I placed the tilda because I am not entirely sure what the height was), and coordinate is 0, ~, 0 because that is the typical coordinate to fight the ender dragon.

The most recent worlds that I have created have all had similar issues in the other biomes, with the spawn area for the End being generated in an ambiguous location (also with no ground) and it seems that all of the other structures are having the same issue, with akril being the only block that is grouped together in large clumps.

The issue has presented itself over to different playthroughs on the same modpack/version/Forge release. 

Since the game crashes after the Ender Dragon spawns, enclosed is the log for the most recent playthrough.
[crash-2024-11-29_23.29.58-server.txt](https://github.com/user-attachments/files/17964483/crash-2024-11-29_23.29.58-server.txt)

**Comment by 1tech23** [comment]
Please note that I have been through my logs. I do not believe that the mods that Embeddium has reported are the ones causing the issue. There does not seem to be any sort of correlation between the current log and previous versions of my modpack that have used similar modlists. I will continue to investigate the issue.

**Comment by SashaKYotoz** [comment]
What i saw in log - 'insanelib' has problems with rendering ender dragon's related stuff

**Comment by 1tech23** [comment]
> What i saw in log - 'insanelib' has problems with rendering ender dragon's related stuff

I apologize, I forgot to mark this issue as closed when I solved it yesterday. It turns out that it had nothing to do with End's Phantasm. I made a poor assumption and assumed that it was because of the fact that the features that End's Phantasm added weren't loading correctly either.
