### ISSUE TITLE
Marked as 1.20.6 compatible on modrinth but it doesn't work on 1.20.6

### ISSUE THREAD

**Issue by nickademas** [Lyof429/EndsPhantasm#6]
![obraz](https://github.com/Lyof429/EndsPhantasm/assets/46594867/c8e7d321-f31d-49fd-ac25-8d2a610a3f22)

**Comment by Lyof429** [comment]
Oops sorry, modrinth auto detects the version from the file so forgot to set it correctly 
It's only made for 1.20.1. If it works on anything else, it's pure luck
