### ISSUE TITLE
Doesn't teleport you to the end islands first

### ISSUE THREAD

**Issue by YnwLNE** [Lyof429/EndsPhantasm#9]
Using the forge version of 0.3 and it still teleports to the main island instead of the outer ones (I heavily agree that this should be the way vanilla does it). I do have some other mods that tweak the end so maybe they are a conflict?

Other mods:
The outer end
Nullscape
l_ender's cataclysm (technically)
True Ending: Ender Dragon Overhaul

**Comment by Lyof429** [comment]
Nah sorry, it's just the forge version
Redirect mixins are a bit unstable on forge and the porter wasn't able to get them to work properly, so this feature is fabric only for now

**Comment by YnwLNE** [comment]
damn, nice mod though
